### ISSUE TITLE
Remove "logging" module import and usage from fit methods modules

### ISSUE THREAD

**Issue by Neverhorst** [Ulm-IQO/qudi#133]
The fit methods modules (linearmethods, lorentzianlikemethods etc.) are still importing and using the old, obsolete logging module from previous qudi versions. This will most probably result in an error when the lines containing things like "logger.warning('Issue this warning!')" are executed.

So in all fit modules the import lines similar to:
`import logging`
`logger = logging.getLogger(__name__)`
have to be removed.

Also all lines similar to
`logger.warning(...)`
have to be changed to
`self.log.warning(...)`

Changes have already been done in "linearmethods" if you want to see an example.

**Comment by christoph-mueller** [comment]
changes done

**Comment by a-stark** [comment]
I was wondering why the logging module was removed from the fitmethods? In fact, this way of using the logging module should not interfere with the qudi logger, since it will be collected from the core logger of qudi. More information about that can be found [in the documentation](https://ulm-iqo.github.io/qudi-generated-docs/html-docs/logger_usage.html).
If logger.* is replaced by the qudi's internal log.* call, then fit_logic_standalone.py in the tools directory cannot be used and will throw an errors in case of using this attribute. However, this can be solved very quick in attaching the logger as an attribute in the fit_logic_standalone.py init method.

The drawback of this procedure is that you will not be able to locate the exact fitmethod file in the log message, since all messages will be related to the main module FitLogic (which is situated in fit_logic.py). It might compromise the users ability to search for the specific error log.

**Comment by Neverhorst** [comment]
Well, we put some effort into changing it in every module back when this logging change has been introduced to qudi. So the idea was why are the fit modules any different than any other module? The argument about better bug-tracking is of course right but since all methods are attached to FitLogic I got the feeling that this is not really a false behavior if the logic is reporting errors (warnings, infos, debugs).

Standalone modules are in my opinion no reason to alter qudi conventions.

If this was a wrong step we should discuss it in the software meeting. I just opened this issue mainly to discuss it.

**Comment by a-stark** [comment]
Essentially, I am not against the general concept and I agree with @Neverhorst.
The emphasis was maybe more on the question, whether we want to maintain a fit_logic_standalone.py, which works without direct inheritance of qudi logic base classes (and therefore without the log attribute) and which serves as a test script for the fit methods?
The other part of the comment was more towards the flexible logging behavior of qudi.

**Comment by jochen-scheuer** [comment]
In my opinion the fit logic standalone is very useful! Like this the postprocessing of data can be done with the same fits and while postprocessing changes and improvements of the fit logic will also contribute to qudi!

**Comment by Neverhorst** [comment]
Agree, @jochen-scheuer, and it's not about abandoning the standalone module. I suggest we stick to the convention with self.log.<messagetype>() like in any other module and just attach the logger in the __init__() of the standalone module. If we make an exception by explicitly importing the logger, we should do it in the standalone modules only. (because they are not really a part of qudi)

**Comment by Neverhorst** [comment]
Just commited the proposed changes to the standalone module. Seems to work. (see commit 683f31c673aa5d79714a642c4990bf1d6cdad502)

**Comment by a-stark** [comment]
I would also agree with this procedure. I think we could prevent long searchings for a info/warning/error message in the code, if the messages are kept not too general (like 'fit method failed'), but rather more specific for each fit method (like: 'the two lorentz fit failed'). Typo errors or other exceptions, which might happen within a method contain anyway a proper and explicit Traceback to the file and linenumber.

I would close this issue today, if nobody has another opinion.
