### ISSUE TITLE
Does set_up_line() needs to be in the ConfocalScannerInterface?

### ISSUE THREAD

**Issue by Neverhorst** [Ulm-IQO/qudi#152]
It appears to me as if the interface method set_up_line() is just a helper method for the method scan_line(). Only the latter needs to be accessed by external logic modules yet both are part of the ConfocalScannerInterface. Is that right?

**Comment by drogenlied** [comment]
That seems to be the case.
set_up_line does not need to be in the interface or any interfuse and is purely internal.

**Comment by kay-jahnke** [comment]
Indeed, this function is only called by the ni-hardware itself (and the same for the dummy). So it is not needed in the interface, especially since its function is quite trivial.

So I deleted the function from the interface and made it private in ni_card and dummy_scanner by adding a leading underscore. Tested dummy, and everything works fine in commit b37a7d9.

Issue closed!
