### ISSUE TITLE
install-python-modules-windows.bat fails on Windows 10

### ISSUE THREAD

**Issue by mvbnano** [Ulm-IQO/qudi#360]
## *What* is affected by this bug?
New qudi conda environments are unable to be created on Windows 10 by running ```install-python-modules-windows.bat```. This is true for both 32-bit and 64-bit Windows 10 PCs.

## *When* does this occur?
When a user attempts to run ```install-python-modules-windows.bat``` from the command line an error occures (see below).

## *Where* on the platform does it happen?
The error generated is:
```
EnvironmentLocationNotFound: Not a conda environment
```

## *How* do we replicate the issue?
Run ```install-python-modules-windows.bat``` on 32-bit or 64-bit Windows 10.

## Expected behavior (i.e. solution)
I get around this problem by simply entering the last command in ```install-python-modules-windows.bat``` to create the environment:
```
conda env create -f conda-env-win8-qt5.yml
```

## Screenshot
![img_20180405_150409](https://user-images.githubusercontent.com/13956283/38396524-d1487234-397b-11e8-993f-ac12323eb0bd.jpg)

**Comment by kay-jahnke** [comment]
I have installed qudi on quite a few Win10 machines but never had this problem.

* I had however needed to set the path variable manually (as described [here](https://medium.com/@GalarnykMichael/install-python-on-windows-anaconda-c63c7c3d1444)). 
* Also you may need to run your console as administrator in some cases.

With these two caveats in mind it always worked without any problems.

**Comment by SimonSchmitt88** [comment]
I have seen the same problem on the laptops of two Chinese colleagues (no idea if that is coincidence or not?) 
We checked the path variable and ran the console as administrator, so I do not think that this is the problem. 
Our solution was to comment out the third line from the bottom (56), which seems to be the problem, If I understand this line, it tries to delete the (old) qudi enviroment and if there is none, an error occurs.

**Comment by drogenlied** [comment]
Just a short reminder about two things:
 * Windows 10 is not a Windows version. Every 6 months there is a new version that can be significantly incompatible with previous versions. If you have automatic updates enabled, software on your computer may break in funny, tragic and unforeseen ways. Examples for what Windows versions are: Windows 10 build 1507, Windows 10 build 1703. When reporting bugs in Qudi, specify the exact Windows version.
 * Not a single version of Windows 10 is officially supported by Qudi.

**Comment by mvbnano** [comment]
Thank you for the input and comments @kay-jahnke and @drogenlied . This issue doesn't really bother me as I know how to fix it, but I thought it may be appropriate to raise as it could discourage any new users from transitioning to the platform.

**Comment by a-stark** [comment]
I encountered the same problem arises [from this line](https://github.com/Ulm-IQO/qudi/blob/6ce1fe482c3be0e367880ea2ba7ca158741de4a0/tools/install-python-modules-windows.bat#L56) in the [installation script](https://github.com/Ulm-IQO/qudi/blob/master/tools/install-python-modules-windows.bat). 
Apparently conda has changed its notification status, i.e. if you try to remove an non-existing environment, it will throw an expection, which will stop the script, instead of just mutually acknowledge that the environment is not there. Till now, I did not find a way to catch properly the exception (this is in windows cmd, and such a thing seems not to exist here, what a poor terminal...). I think the proper way to go is to outsource the environment creation stuff in a powershell script (here you have more possibilites), and to call this from the bat script.
