### ISSUE TITLE
Get Confocal Image does not get the image bounds correctly the first time

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#57]
Migration: trac#42.

Steps to reproduce:
 * Make confocal scan.
 * Open PoiManager, the confocal image is loaded automatically.
 * Make a new scan with different ranges.
 * Click Get Confocal Image. The image data updates, but the position does not.
 * Click Get Confocal Image again. Now the position of the scan is updated correctly.

**Comment by kay-jahnke** [comment]
@drogenlied : I tried with dummy configuration and a clean App-Status to reproduce the bug.
I can't find anything wrong with the POI-Manager. Everything works for me and the axis gets updated to the new range.

The only thing I noticed was that in confocal, after changing the scan-region, the crosshair was outside the scan, but the picture scaled nicely, so that was OK.

**Comment by drogenlied** [comment]
I cannot reproduce this on a real setup either, it must have been fixed by other changes.
Feel free to close this issue.

**Comment by kay-jahnke** [comment]
Issues seems to have been resolved sometime in the past.
