### ISSUE TITLE
Pulser hardware "set functions" return values

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#67]
Migration: trac#72.

Implement all functions in Hardware that set a parameter like "set_sampling_rate()" so that they set the parameter in hardware, ask the hardware afterwards what is set and return this value.
In the logic that calls this function the return value should be taken as current value and not the one that was given as set value.
This will avoid conflicts when the logic wants to set a value that can not be met by the hardware. For example the sample rate of the AWG must be a number that is representable by a division of two integers in a certain range (multiplier and divider of the clock generator), i.e. it can not represent each floating point frequency you enter. This could cause rounding errors.

**Comment by Neverhorst** [comment]
Has been fixed a long time ago for present hardware modules. If the hardware is not returning these values, the logic will complain at some point. But since these changes have been introduced some time ago and nobody had issues regarding this ticket, I will close it. If at some point problems occur using a specific type of pulser hardware, a new issue should be opened for that device.
