### ISSUE TITLE
Implement proper handling of the pp-Voltage for the sequence_generator_logic

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#87]
Migration: trac#201.

This is currently an attribute of the logic and needs to be properly set from the GUI.

**Comment by Neverhorst** [comment]
Well sort of... The SequenceGeneratorLogic is now able to handle this parameter properly and upon activation the voltages are read from the device.
There is however a settings dialogue missing in the GUI to edit these values per channel.
I postponed and then forgot this point because this raises the question if ALL widgets for "hardware settings" of the pulse generator should be residing in a separate settings dialogue. (adding the pp-voltage widgets is too much for the main window)

**Comment by Neverhorst** [comment]
Introduced the above mentioned dialog box. So #384 will fix this issue.

**Comment by Neverhorst** [comment]
Fixed by PR #384
